using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace WTangent.Components;

/// <summary>增量源生成器（scope 式依赖收集）：为手写 Entry 服务——
/// 收集 [AgentComponent] 标记的 Command 子类 + [AgentTool] 标记的 ITool 实现类，
/// 生成 partial class Entry 的另一半（CollectedCommands / CollectedTools 属性）；
/// 手写 Entry 里接线（Commands => CollectedCommands）。Entry 生命周期归手写。</summary>
[Generator]
public sealed class AgentComponentGenerator : IIncrementalGenerator
{
    private const string ComponentAttr = "WTangent.Components.AgentComponentAttribute";
    private const string ToolAttr = "WTangent.Components.AgentToolAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 收集 [AgentComponent] 类（CreateSyntaxProvider：不依赖 ForAttributeWithMetadataName 的匹配怪癖）
        var commands = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => GetAttributedClass(ctx, ComponentAttr))
            .Where(static s => s is not null)
            .Select(static (s, _) => s!)
            .Collect();

        // 收集 [AgentTool] 类（LLM 工具）
        var tools = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => GetAttributedClass(ctx, ToolAttr))
            .Where(static s => s is not null)
            .Select(static (s, _) => s!)
            .Collect();

        // 项目 RootNamespace（生成 Entry partial 的命名空间）
        var rootNs = context.AnalyzerConfigOptionsProvider
            .Select(static (p, _) =>
            {
                p.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                return ns is { Length: > 0 } ? ns : "Agent";
            });

        context.RegisterSourceOutput(
            commands.Combine(tools).Combine(rootNs),
            static (spc, pair) => Emit(spc, pair.Left.Left, pair.Left.Right, pair.Right));
    }

    private static INamedTypeSymbol? GetAttributedClass(GeneratorSyntaxContext ctx, string attrFullName) =>
        ctx.Node is ClassDeclarationSyntax cls
        && ctx.SemanticModel.GetDeclaredSymbol(cls) is INamedTypeSymbol sym
        && HasAttribute(sym, attrFullName) ? sym : null;

    private static bool HasAttribute(ISymbol symbol, string attrFullName) =>
        symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == attrFullName);

    private static void Emit(SourceProductionContext spc, ImmutableArray<INamedTypeSymbol> commands,
        ImmutableArray<INamedTypeSymbol> tools, string rootNs)
    {
        if (commands.IsDefaultOrEmpty && tools.IsDefaultOrEmpty) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Components.AgentComponentGenerator />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Entry 的生成部分（依赖收集产物）：手写 partial Entry 里接线（Commands => CollectedCommands 等）</summary>");
        sb.AppendLine("    public sealed partial class Entry");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>收集的组件命令（[AgentComponent]）</summary>");
        sb.AppendLine("        private static System.CommandLine.Command[] CollectedCommands =>");
        sb.AppendLine("        [");
        foreach (var cmd in commands)
        {
            var name = GetCommandName(cmd);
            var fullType = cmd.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            new {fullType}(),   // {name}");
        }
        sb.AppendLine("        ];");
        sb.AppendLine("        /// <summary>收集的 LLM 工具（[AgentTool]）</summary>");
        sb.AppendLine("        private static WTangent.Core.ITool[] CollectedTools =>");
        sb.AppendLine("        [");
        foreach (var t in tools)
        {
            var fullType = t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            new {fullType}(),   // {t.Name}");
        }
        sb.AppendLine("        ];");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("Entry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string GetCommandName(INamedTypeSymbol cmd)
    {
        foreach (var kv in cmd.GetAttributes()
                     .Where(attr => attr.AttributeClass?.ToDisplayString() == ComponentAttr)
                     .SelectMany(attr => attr.NamedArguments))
        {
            if (kv is { Key: "Name", Value.Value: string { Length: > 0 } s })
                return s;
        }
        var name = cmd.Name;
        const string suffix = "Command";
        if (name.EndsWith(suffix, StringComparison.Ordinal) && name.Length > suffix.Length)
            name = name.Substring(0, name.Length - suffix.Length);
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
