using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace WTangent.Components;

/// <summary>增量源生成器：完整生成组件入口 Entry——
/// Commands = 收集 [AgentComponent] 标记的 Command 子类（serve/tui/gui/cmd 共用，无标注时为空数组）；
/// Default = [AgentDefault] 标记的静态方法（未标记则 null）；
/// Tools = 收集 [AgentTool] 标记的 ITool 实现类（tool 组件用；非 tool 组件不生成，不引入 Core 引用）。
/// 生成目标命名空间 = 项目 RootNamespace。组件不再手写 Entry。</summary>
[Generator]
public sealed class AgentComponentGenerator : IIncrementalGenerator
{
    private const string ComponentAttr = "WTangent.Components.AgentComponentAttribute";
    private const string DefaultAttr = "WTangent.Components.AgentDefaultAttribute";
    private const string ToolAttr = "WTangent.Components.AgentToolAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 收集 [AgentComponent] 类。注意：不用 ForAttributeWithMetadataName——
        // Roslyn 5.3 在编译引用含某些类型（如 WTangent.Core.Application）时该 API 静默收集为空，
        // 改用 CreateSyntaxProvider + 语义模型特性检查（兼容所有 Roslyn 版本）。
        var commands = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => GetAttributedClass(ctx, ComponentAttr))
            .Where(static s => s is not null)
            .Select(static (s, _) => s!)
            .Collect();

        // 标记了 [AgentDefault] 的方法（组件顶级行为；0 或 1 个）
        var defaults = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is MethodDeclarationSyntax,
                static (ctx, _) => GetAttributedMethod(ctx, DefaultAttr))
            .Where(static s => s is not null)
            .Select(static (s, _) => s!)
            .Collect();

        // 标记了 [AgentTool] 的类（LLM 工具）
        var tools = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => GetAttributedClass(ctx, ToolAttr))
            .Where(static s => s is not null)
            .Select(static (s, _) => s!)
            .Collect();

        // 项目 RootNamespace（生成 Entry 的命名空间）
        var rootNs = context.AnalyzerConfigOptionsProvider
            .Select(static (p, _) =>
            {
                p.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                return ns is { Length: > 0 } ? ns : "Agent";
            });

        context.RegisterSourceOutput(
            commands.Combine(defaults).Combine(tools).Combine(rootNs),
            static (spc, pair) => Emit(spc, pair.Left.Left.Left, pair.Left.Left.Right, pair.Left.Right, pair.Right));
    }

    private static INamedTypeSymbol? GetAttributedClass(GeneratorSyntaxContext ctx, string attrFullName) =>
        ctx.Node is ClassDeclarationSyntax cls
        && ctx.SemanticModel.GetDeclaredSymbol(cls) is INamedTypeSymbol sym
        && HasAttribute(sym, attrFullName) ? sym : null;

    private static IMethodSymbol? GetAttributedMethod(GeneratorSyntaxContext ctx, string attrFullName) =>
        ctx.Node is MethodDeclarationSyntax mtd
        && ctx.SemanticModel.GetDeclaredSymbol(mtd) is IMethodSymbol sym
        && HasAttribute(sym, attrFullName) ? sym : null;

    private static bool HasAttribute(ISymbol symbol, string attrFullName) =>
        symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == attrFullName);

    private static void Emit(SourceProductionContext spc, ImmutableArray<INamedTypeSymbol> commands,
        ImmutableArray<IMethodSymbol> defaults, ImmutableArray<INamedTypeSymbol> tools, string rootNs)
    {
        if (commands.IsDefaultOrEmpty && tools.IsDefaultOrEmpty && defaults.Length == 0) return;
        if (defaults.Length > 1)
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("AGEN001", "AgentDefault 重复",
                    "组件只能有一个 [AgentDefault] 方法，发现 {0} 个", "Components",
                    DiagnosticSeverity.Error, true),
                Location.None, defaults.Length));
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Components.AgentComponentGenerator />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNs}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>组件入口（空壳 ALC 加载后注册命令）：Commands 自动收集 [AgentComponent]，Default 来自 [AgentDefault]</summary>");
        sb.AppendLine("    public static class Entry");
        sb.AppendLine("    {");
        if (commands.Length > 0)
        {
            sb.AppendLine("        /// <summary>组件命令列表</summary>");
            sb.AppendLine("        public static System.CommandLine.Command[] Commands { get; } =");
            sb.AppendLine("        [");

            foreach (var cmd in commands)
            {
                var name = GetCommandName(cmd);
                var fullType = cmd.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"            new {fullType}(),   // {name}");
            }

            sb.AppendLine("        ];");
        }
        if (defaults.Length == 1)
        {
            var m = defaults[0];
            var fmt = SymbolDisplayFormat.FullyQualifiedFormat.AddMemberOptions(SymbolDisplayMemberOptions.IncludeContainingType);
            sb.AppendLine("        /// <summary>顶级行为（[AgentDefault] 标记的方法）</summary>");
            sb.AppendLine($"        public static System.Func<string[], int>? Default => {m.ToDisplayString(fmt)};");
        }
        else
        {
            sb.AppendLine("        /// <summary>顶级行为：无 [AgentDefault] 标记 → null（必须显式子命令）</summary>");
            sb.AppendLine("        public static System.Func<string[], int>? Default => null;");
        }
        if (tools.Length > 0)
        {
            sb.AppendLine("        /// <summary>LLM 工具列表（[AgentTool] 标记的 ITool 实现，serve 加载 tool 组件时合并）</summary>");
            sb.AppendLine("        public static WTangent.Core.ITool[] Tools { get; } =");
            sb.AppendLine("        [");
            foreach (var t in tools)
            {
                var fullType = t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"            new {fullType}(),   // {t.Name}");
            }
            sb.AppendLine("        ];");
        }
        // 运行时上下文：宿主（空壳 Client 接收器）启动时注入同一 WtAgentApp 引用；
        // 组件代码经 Entry.App 访问 Logger/Events/Config/Store/Remote/Services（组件间不互引 dll）
        sb.AppendLine("        /// <summary>运行时上下文（宿主注入；引用同一实例，组件与宿主共享状态）</summary>");
        sb.AppendLine("        public static WTangent.Core.Application? App { get; set; }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("Entry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string GetCommandName(INamedTypeSymbol cmd)
    {
        foreach (var kv in cmd.GetAttributes()
                     .Where(attr => attr.AttributeClass?.ToDisplayString() == ComponentAttr)
                     .SelectMany(attr => attr.NamedArguments))
        {
            if (kv is { Key: "Name", Value.Value: string { Length: > 0 } s })
                return s;
        }
        var name = cmd.Name;
        const string suffix = "Command";
        if (name.EndsWith(suffix, StringComparison.Ordinal) && name.Length > suffix.Length)
            name = name.Substring(0, name.Length - suffix.Length);
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
